export const buttonData = [
  { label: "N/A", value: "N/A", id: "1" },
  {
    label: "COVID-Mask (EHD)",
    value: "COVID-Mask (EHD)",
    id: "2",
  },
  { label: "Dwenguino", value: "Dwenguino", id: "3" },
  { label: "AeroSpec", value: "AeroSpec", id: "4" },
  { label: "Ammonia", value: "Ammonia", id: "5" },
  {
    label: "Aero Propulsion (Private)",
    value: "Aero Propulsion (Private)",
    id: "6",
  },
  {
    label: "Aircraft Mechanics",
    value: "Aircraft Mechanics",
    id: "7",
  },
  { label: "Fuzz", value: "Fuzz", id: "8" },
  { label: "STREAM Tools", value: "STREAM Tools", id: "9" },
  { label: "Gamification", value: "Gamification", id: "10" },
  { label: "SUDOKU", value: "SUDOKU", id: "11" },
  { label: "ECoS", value: "ECoS", id: "12" },
  { label: "Udemy", value: "Udemy", id: "13" },
  { label: "WEGO", value: "WEGO", id: "14" },
  { label: "Arduino Sensors", value: "Arduino Sensors", id: "15" },
  { label: "Growing Rod", value: "Growing Rod", id: "16" },
  {
    label: "RV Vectors (Private)",
    value: "RV Vectors (Private)",
    id: "17",
  },
  {
    label: "Computing Skills Building (CSB)",
    value: "Computing Skills Building (CSB)",
    id: "18",
  },
  {
    label: "Drowsy Driving Detection",
    value: "Drowsy Driving Detection",
    id: "19",
  },
  {
    label: "Technical Writing",
    value: "Technical Writing",
    id: "20",
  },
  { label: "Social Media", value: "Social Media", id: "21" },
  { label: "Leadership", value: "Leadership", id: "22" },
  {
    label: "Control Panel Template",
    value: "Control Panel Template",
    id: "23",
  },
  { label: "DietSkan", value: "DietSkan", id: "24" },
  { label: "598 COVID", value: "598 COVID", id: "25" },
  {
    label: "Commercialization",
    value: "Commercialization",
    id: "26",
  },
  {
    label: "DC-to-DC Converter",
    value: "DC-to-DC Converter",
    id: "27",
  },
  {
    label: "COVID-Sensor (Personal Exposure, AeroSpec)",
    value: "COVID-Sensor",
    id: "28",
  },
  {
    label: "COVID-Filter (EHD)",
    value: "COVID-Filter (EHD)",
    id: "29",
  },
  { label: "Stoma", value: "Stoma", id: "30" },
  { label: "FEF Sensors", value: "FEF Sensors", id: "31" },
  { label: "Pesticides", value: "Pesticides", id: "32" },
];
